[features]
seeds = false
skip-lint = false
[programs.localnet]
re_initialization = "E627JnBgtEZmTPm3uaToW1nfTKmW4x9svAknrWfTZEVs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
