[features]
seeds = false
skip-lint = false
[programs.localnet]
type_cosplay = "C1SBUQVojZ8KwHKRCrVLQp37GTJjotL9w3pXFK72pGxA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
