[features]
seeds = false
skip-lint = false
[programs.localnet]
account_data_matching = "HFeMKELQjfX6vCM79KNWbAQWVyviRqjQQn56dN7AmsSE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
