[features]
seeds = false
skip-lint = false
[programs.localnet]
arb_cpi = "7nZ7zriZRV7UKWDsaB6kFGKguc5AbdVC4av6vdJnzpqs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
